name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual
    inputs:
      message:
        description: "Generate snake animation"
        default: "Manual trigger"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Generate Snake Animation
      run: python snake.py --output github-contribution-grid-snake.svg

    - name: Commit and Push Snake Animation
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add github-contribution-grid-snake.svg
        git commit -m "Updated Snake Animation" || echo "No changes to commit"
        git push
